"""Increased size limit

Revision ID: 7e829096dc5a
Revises: 
Create Date: 2024-10-14 22:39:22.306333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e829096dc5a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.alter_column('text_content',
               existing_type=sa.VARCHAR(length=400),
               type_=sa.String(length=500),
               existing_nullable=True)

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('url',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=150),
               existing_nullable=False)
        batch_op.alter_column('htmlfile',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=155),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('htmlfile',
               existing_type=sa.String(length=155),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.alter_column('url',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.alter_column('text_content',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=400),
               existing_nullable=True)

    # ### end Alembic commands ###
