"""Added author column to posts

Revision ID: 9ae6fccdc7c9
Revises: 7e829096dc5a
Create Date: 2024-10-19 10:05:41.743564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ae6fccdc7c9'
down_revision = '7e829096dc5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author', sa.String(length=75), nullable=False, server_default='Shashank Shetty'))

    op.alter_column('post', 'author', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('author')

    # ### end Alembic commands ###
